# Afrique
---
!model.SearchDefinition
text: bembeya jazz national
---
!model.SearchDefinition
text: syliphone 
---
!model.SearchDefinition
text: keletigui
---
!model.SearchDefinition
text: mali
---
!model.SearchDefinition
text: guinee
---
!model.SearchDefinition
text: benin
---
!model.SearchDefinition
text: ghana
---
!model.SearchDefinition
text: pivi et les balladins
---
!model.SearchDefinition
text: balla et ses balladins
---
!model.SearchDefinition
text: gyasi
---
!model.SearchDefinition
text: african head charge
---
!model.SearchDefinition
text: dub syndicate
---
!model.SearchDefinition
text: on-u sound

# Pop
---
!model.SearchDefinition
text: will oldham
include_description: False 
---
!model.SearchDefinition
text: stereolab
include_description: False
---
!model.SearchDefinition
text: throbbing gristle
include_description: False

# ost / library
---
!model.SearchDefinition
text: bruno nicolai
---
!model.SearchDefinition
text: guido de angelis
---
!model.SearchDefinition
text: amedeo tommasi
---
!model.SearchDefinition
text: piero umiliani
---
!model.SearchDefinition
text: dagored
---
!model.SearchDefinition
text: stroboscopica
---
!model.SearchDefinition
text: morricone
include_description: False
---
!model.SearchDefinition
text: april orchestra rca
exact_match: False
---
!model.SearchDefinition
text: puccio roelens
---
!model.SearchDefinition
text: rino de filippi
---
!model.SearchDefinition
text: st germain des pres
---
!model.SearchDefinition
text: italy library
exact_match: False
include_description: False
---
!model.SearchDefinition
text: alessandro alessandroni
---
!model.SearchDefinition
text: coloursound
---
!model.SearchDefinition
text: easy tempo


# bresil
---
!model.SearchDefinition
text: elenco
include_description: False
---
!model.SearchDefinition
text: gilberto gil
---
!model.SearchDefinition
text: jorge ben
---
!model.SearchDefinition
text: mpb4
---
!model.SearchDefinition
text: quarteto em cy
---
!model.SearchDefinition
text: ze keti
---
!model.SearchDefinition
text: nara leao
---
!model.SearchDefinition
text: edu lobo
---
!model.SearchDefinition
text: grupo manifesto
---
!model.SearchDefinition
text: novos baianos


# electronique
---
!model.SearchDefinition
text: shandar
---
!model.SearchDefinition
text: steve reich
---
!model.SearchDefinition
text: pandit pran nath
auction_only: False
---
!model.SearchDefinition
text: ariel kalma
---
!model.SearchDefinition
text: camille sauvage
---
!model.SearchDefinition
text: philip glass
---
!model.SearchDefinition
text: jon gibson
---
!model.SearchDefinition
text: leimer
---
!model.SearchDefinition
text: prima materia
---
!model.SearchDefinition
text: roberto musci
---
!model.SearchDefinition
text: bernard parmegianni
---
!model.SearchDefinition
text: luc ferrari
---
!model.SearchDefinition
text: chatham square
---
!model.SearchDefinition
text: terry riley
---
!model.SearchDefinition
text: glenn branca
---
!model.SearchDefinition
text: roberto cacciapaglia
---
!model.SearchDefinition
text: oneohtrix
---
!model.SearchDefinition
text: futuro antico
---
!model.SearchDefinition
text: jd emmanuel
---
!model.SearchDefinition
text: bitchin bajas
---
!model.SearchDefinition
text: charlemagne palestine
---
!model.SearchDefinition
text: annie anxiety

# jazz
---
!model.SearchDefinition
text: alice coltrane
---
!model.SearchDefinition
text: pharoah sanders
---
!model.SearchDefinition
text: spiritual jazz
